import sys
import os

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")

from password_utils import hash_password, verify_password
from humor_utils import get_efficiency_label, get_hacker_title, get_uselessness_meter
from services import AuthService, HolidayService, LeaveService, PlanService, UserService
from algorithm import HolidayOptimizer
from models import HolidayPlan
from datetime import date

def run_tests():
    print("========================================")
    print("Running Holiday Hacker Verification Suite")
    print("========================================")

    # 1. Password Utils
    p_hash = hash_password("test123")
    assert verify_password("test123", p_hash), "Password verification failed"
    assert not verify_password("wrong", p_hash), "Password negative test failed"
    print("[PASS] Password utils test passed.")

    # 2. Humor Utils
    assert "LEGENDARY" in get_efficiency_label(5.0)
    assert "Calendar Wizard" in get_hacker_title(12)
    meter = get_uselessness_meter(4.0, 5, 10)
    assert len(meter) == 4
    print("[PASS] Humor utils test passed.")

    # 3. Auth Service
    auth = AuthService()
    user = auth.login("testuser", "test123")
    assert user is not None and user.role == "user", "User login failed"
    print(f"[PASS] User login test passed: {user.name} ({user.role})")

    admin = auth.login("admin", "admin123")
    assert admin is not None and admin.role == "admin", "Admin login failed"
    print(f"[PASS] Admin login test passed: {admin.name} ({admin.role})")

    bad_user = auth.login("testuser", "wrongpassword")
    assert bad_user is None, "Negative login test failed"
    print("[PASS] Invalid login test passed.")

    # 4. Holiday Service
    h_service = HolidayService()
    h_count = h_service.get_holiday_count()
    assert h_count > 0, "No holidays found in database"
    h_range = h_service.get_holidays_in_range(date(2026, 1, 1), date(2026, 12, 31))
    assert len(h_range) > 0, "No holidays in 2026 range"
    print(f"[PASS] Holiday service test passed: {h_count} total holidays, {len(h_range)} in 2026.")

    # 5. Leave Service
    l_service = LeaveService()
    test_date = date(2026, 11, 20)
    for lv in l_service.get_user_leaves(user.id):
        if lv.leave_date == test_date:
            l_service.delete_leave(lv.id)

    l_service.add_leave(user.id, test_date)
    leaves_after = [l for l in l_service.get_user_leaves(user.id) if l.leave_date == test_date]
    assert len(leaves_after) == 1, "Leave was not added"
    l_service.delete_leave(leaves_after[0].id)
    print("[PASS] Leave service CRUD test passed.")

    # 6. Algorithm Test (October 2026 Gandhi Jayanti / Dussehra test case)
    optimizer = HolidayOptimizer()
    holidays_oct = h_service.get_holidays_in_range(date(2026, 10, 1), date(2026, 10, 31))
    strategies = optimizer.find_best_strategies(date(2026, 10, 1), date(2026, 10, 31), holidays_oct, [], 5)
    assert len(strategies) > 0, "No strategies generated by optimizer"
    best = strategies[0]
    print(f"[PASS] Algorithm test passed: Found {len(strategies)} strategies. Top strategy: {best.total_days} days off with {best.leaves_needed} leaves ({best.efficiency:.1f}x efficiency).")

    # 7. Plan Service
    p_service = PlanService()
    sample_plan = HolidayPlan(
        id=0,
        user_id=user.id,
        plan_name="Automated Test Plan",
        start_date=date(2026, 10, 1),
        end_date=date(2026, 10, 5),
        leaves_used=1,
        consecutive_days=5,
        efficiency=5.0,
        recommended_dates=[date(2026, 10, 2)]
    )
    plan_id = p_service.save_plan(sample_plan)
    assert plan_id > 0, "Plan not saved"
    user_plans = p_service.get_user_plans(user.id)
    assert any(p.id == plan_id for p in user_plans), "Saved plan not found in user plans"
    p_service.delete_plan(plan_id)
    print("[PASS] Plan service CRUD test passed.")

    # 8. User Service (Admin)
    u_service = UserService()
    users = u_service.find_all_users()
    assert len(users) > 0, "Users list is empty"
    print(f"[PASS] Admin user service test passed: {len(users)} standard users found.")

    print("========================================")
    print("ALL TESTS PASSED SUCCESSFULLY!")
    print("========================================")

if __name__ == "__main__":
    run_tests()
